export const supportedGiftCards = [
  {
    id: "AMAZON",
    name: "Amazon",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Famazon_image.png?alt=media&token=f354ae5d-b4fd-466c-b08a-883a71e0abb0",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "INR",
      "BRL",
    ],
  },
  {
    id: "APPLE",
    name: "Apple",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fapple_image.png?alt=media&token=add7daa3-6973-4aca-8167-bb9b0fb044ba",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "INR",
      "BRL",
    ],
  },
  {
    id: "BINANCE",
    name: "Binance",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fbinance.png?alt=media&token=a73d61db-3622-42f4-8a33-38c08430db72",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "INR",
      "BRL",
    ],
  },
  {
    id: "GOOGLE",
    name: "Google",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fgoogle_image.png?alt=media&token=ab5358d8-a8cf-4020-ae27-5216dec7b434",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "INR",
      "BRL",
    ],
  },
  {
    id: "NETFLIX",
    name: "Netflix",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fnetflix-gift-card.webp?alt=media&token=75ef92de-5e9a-430c-a80f-6484d072954e",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "INR",
      "BRL",
    ],
  },
  {
    id: "SPOTIFY",
    name: "Spotify",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fspotify.jpeg?alt=media&token=75adb77b-c4a3-4c4d-92b9-da4f5b0fedf3",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "INR",
      "BRL",
    ],
  },
  {
    id: "STEAM",
    name: "Steam",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fsteam_image.png?alt=media&token=3469deed-caa1-418d-a206-6e55653b0422",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "INR",
      "BRL",
    ],
  },
  {
    id: "XBOX",
    name: "Xbox",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fxbox_image.png?alt=media&token=be9c8b24-939e-45ff-867d-a9594f027153",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "INR",
      "BRL",
    ],
  },
  {
    id: "PLAYSTATION",
    name: "Playstation",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fplaystation_image.png?alt=media&token=2f066fd0-b0e9-4f61-b54a-fe4f06542ac3",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "INR",
      "BRL",
    ],
  },
  {
    id: "NINTENDO",
    name: "Nintendo",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fnintendo.png?alt=media&token=dac274eb-484e-4d1e-80b4-5ad217d251bc",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "INR",
      "BRL",
    ],
  },
  {
    id: "PAYPAL",
    name: "Paypal",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fpaypal.jpeg?alt=media&token=e341a280-e1f7-4d28-bcb6-0c69243d3f88",
    currency: ["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "BRL"],
  },
  {
    id: "PI",
    name: "Pi",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fpi_image.png?alt=media&token=5297ef09-a05e-4a51-a568-e52ed8272cb4",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "NGN",
      "BRL",
    ],
  },
  {
    id: "PLAYSTATION",
    name: "Playstation",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fplaystation_image.png?alt=media&token=2f066fd0-b0e9-4f61-b54a-fe4f06542ac3",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "NGN",
      "BRL",
    ],
  },
  {
    id: "RAZOR",
    name: "Razor",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Frazor_image.png?alt=media&token=33a8490a-be4b-4b7c-b214-622e61a89e2e",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "NGN",
      "BRL",
    ],
  },
  {
    id: "RIPPLE",
    name: "Ripple",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fripple.png?alt=media&token=d060ce6e-9299-4da9-9c35-495466f61303",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "NGN",
      "BRL",
    ],
  },
  {
    id: "BITCOIN",
    name: "Bitcoin",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fbitcoin.jpg?alt=media&token=a86c9f6a-4c73-444e-8c4c-deefa6af0b09",
    currency: ["USD", "GBP", "EUR", "JPY", "CAD", "AUD", "CNY", "MXN", "BRL"],
  },
  {
    id: "BAMBA",
    name: "Bamba",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fphoto_2023-07-18_16-05-46.jpg?alt=media&token=67cdd44e-2bb6-431f-992e-547cf830be64",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "NGN",
      "BRL",
    ],
  },
  {
    id: "VANILLA",
    name: "Vanilla",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fvanilla_image.png?alt=media&token=6f322727-fb4a-463a-a758-c2bccce10371",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "NGN",
      "BRL",
    ],
  },
  {
    id: "WALMART",
    name: "Walmart",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fwalmart_image.png?alt=media&token=a542089b-6a92-4f7b-9a41-3c614c71e675",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "INR",
      "BRL",
    ],
  },
  {
    id: "GAMESTAR_REWARD_CARD",
    name: "GameStar Reward Card",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2Fgamestar.png?alt=media&token=ed3571ee-3b5a-4824-b863-fba1d93d74d7",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "NGN",
      "BRL",
    ],
  },
  {
    id: "SURE_TRADE_REWARD_CARD",
    name: "Sure Trade Reward Card",
    image:
      "https://firebasestorage.googleapis.com/v0/b/sure-trade-b1a6b.appspot.com/o/Giftcards%2FsureTrade.png?alt=media&token=c9b23be3-b646-4440-a1b8-d38af5f75509",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "NGN",
      "BRL",
    ],
  },
  {
    id: "CHIPPER_CASH",
    name: "Chipper Cash",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlxROgpjuukfHRG5bVkpWp9Y6kcE1PLja5fA&usqp=CAU",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "INR",
      "BRL",
      "NGN",
      "GHS",
    ],
  },
  {
    id: "EBAY",
    name: "Ebay",
    image:
      "https://giftcardshub.com.ng/wp-content/uploads/2021/05/ebaaay-1200x675.jpg",
    currency: [
      "USD",
      "GBP",
      "EUR",
      "JPY",
      "CAD",
      "AUD",
      "CNY",
      "MXN",
      "INR",
      "BRL",
      "NGN",
      "GHS",
    ],
  },
];
