services:
  sure-trade-api-v3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sure-trade-api-v4
    ports:
      - "4007:4007"
    restart: unless-stopped
    networks:
      - sure-trade-network
    environment:
      DB_NAME: sure-trade-db
      DB_USERNAME: root
      DB_PASSWORD:
      DB_HOST: sure-trade-db
      DB_PORT: 3306
      DB_DIALECT: mysql
      DB_SSL_REQUIRE: true
      DB_TIMEZONE: +03:00
      DB_LOGGING: false
      DB_POOL_MAX: 70
      DB_POOL_MIN: 2
      DB_POOL_ACQUIRE: 30000
      DB_POOL_IDLE: 10000
      DB_SYNC: true
      DB_FORCE: false
      LOG_LEVEL: info
      LOG_FILE: logs/app.log
      PORT: 4007
      JWT_SECRET: jwt_secret
      JWT_EXPIRATION_TIME: 24h
      JWT_ALGORITHM: HS256
      OTP_EXPIRATION_TIME: 300
      LOGIN_OTP_EXPIRATION_TIME: 1440
      API_BASE_ROUTE: /api/v2
      FRONTEND_BASE_URL: sureadmin.gamestar.exchange
      BACKEND_BASE_URL: http://20.197.88.9/api/v2
      REDIS_URL: redis://redis:6379
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      NODE_ENV: production
    expose:
      - '3306'
    depends_on:
      - sure-trade-db
      - redis
      - rabbitmq

  sure-trade-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: unless-stopped
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
      - ./my-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sure-trade-network
    links:
      - rabbitmq
    environment:
      MYSQL_DATABASE: sure-trade-db
      MYSQL_ROOT_PASSWORD:
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes

  redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    networks:
      - sure-trade-network
    environment:
      REDIS_PASSWORD:
      REDIS_USERNAME:
      ALLOW_EMPTY_PASSWORD: yes

  rabbitmq:
    image: bitnami/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - sure-trade-network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_SECURE_PASSWORD: no
      #      RABBITMQ_SSL_VERIFY: verify_none
      RABBITMQ_PASSWORD: admin
      RABBITMQ_USERNAME: admin
  #      RABBITMQ_MANAGEMENT_SSL_VERIFY: verify_none
  #      RABBITMQ_MANAGEMENT_BIND_IP: 0.0.0.0

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    networks:
      - sure-trade-network
    environment:
      PMA_HOST: sure-trade-db
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD:
    depends_on:
      - sure-trade-db
  minio:
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - sure-trade-network
    volumes:
      - 'minio_data:/data'
    environment:
      MINIO_ROOT_USER: minio-root-user
      MINIO_ROOT_PASSWORD: minio-root-password
      MINIO_DEFAULT_BUCKETS: sure-trade-storage
      MINIO_SCHEME: http


volumes:
  my-db:
    driver: local
  minio_data:
    driver: local


networks:
  sure-trade-network:
    driver: bridge